version: 2

python:
   version: 3.7
   install:
      - requirements: doc/en/requirements.txt
      - method: pip
        path: .

build:
  os: ubuntu-20.04
  apt_packages:
    - inkscape

formats:
  - epub
  - pdf
